# Generated by Django 5.1.15 on 2026-07-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAlloy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('code', models.CharField(choices=[('LIGA_0', 'Liga 0 — Chumbo puro'), ('LIGA_4', 'Liga 4 — Pb+Estanho'), ('LIGA_5', 'Liga 5 — Negativa'), ('LIGA_6', 'Liga 6 — Positiva')], max_length=16, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('color', models.CharField(default='#1D1D1F', max_length=9, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'liga de chumbo',
                'verbose_name_plural': 'ligas de chumbo',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('start_time', models.TimeField(verbose_name='hora início')),
                ('end_time', models.TimeField(verbose_name='hora fim')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='GridModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nome')),
                ('common_name', models.CharField(blank=True, default='', max_length=60, verbose_name='nome comum')),
                ('positive_plates', models.PositiveSmallIntegerField(default=18, verbose_name='placas positivas')),
                ('negative_plates', models.PositiveSmallIntegerField(default=24, verbose_name='placas negativas')),
                ('shares_grid_with', models.ForeignKey(blank=True, help_text='Ex.: B5L e B7B usam a mesma grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_grid_models', to='catalogs.gridmodel', verbose_name='compartilha grade com')),
            ],
            options={
                'verbose_name': 'modelo de grade',
                'verbose_name_plural': 'modelos de grade',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StopReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('code', models.CharField(blank=True, default='', max_length=30, verbose_name='código')),
                ('description', models.CharField(max_length=160, verbose_name='descrição')),
                ('category', models.CharField(choices=[('MECHANICAL', 'Mecânica'), ('ELECTRICAL', 'Elétrica'), ('MATERIAL', 'Material/matéria-prima'), ('OPERATIONAL', 'Operacional'), ('QUALITY', 'Qualidade'), ('SETUP', 'Setup/troca'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'motivo de parada',
                'verbose_name_plural': 'motivos de parada',
                'ordering': ('category', 'description'),
                'indexes': [models.Index(fields=['category'], name='catalogs_st_categor_4e1436_idx')],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=80, verbose_name='nome/número')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='catalogs.sector', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'máquina',
                'verbose_name_plural': 'máquinas',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['sector'], name='catalogs_ma_sector__39024b_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'sector'), name='unique_machine_per_sector')],
            },
        ),
    ]
