# Generated by Django 5.1.15 on 2026-07-09 11:08
'''
Seed inicial de cadastros-base (Sprint 2):
- Ligas de chumbo (Liga 0/4/5/6) com cores.
- Setores fixos do domínio (Teleiras, Boleira, Moinho, Masseira,
  Empastadeira, Montagem, Formação).
Idempotente (update_or_create por código/nome).
'''

from django.db import migrations


def seed_base(apps, schema_editor):
    Sector = apps.get_model('catalogs', 'Sector')
    LeadAlloy = apps.get_model('catalogs', 'LeadAlloy')

    sectors = [
        'Teleiras', 'Boleira', 'Moinho', 'Masseira',
        'Empastadeira', 'Montagem', 'Formação',
    ]
    for i, name in enumerate(sectors, start=1):
        Sector.objects.update_or_create(name=name, defaults={'is_active': True})

    alloys = [
        {'code': 'LIGA_0', 'name': 'Liga 0 — Chumbo puro', 'color': '#1D1D1F'},
        {'code': 'LIGA_4', 'name': 'Liga 4 — Pb+Estanho',  'color': '#34C759'},
        {'code': 'LIGA_5', 'name': 'Liga 5 — Negativa',    'color': '#FF3B30'},
        {'code': 'LIGA_6', 'name': 'Liga 6 — Positiva',    'color': '#FFCC00'},
    ]
    for a in alloys:
        LeadAlloy.objects.update_or_create(code=a['code'], defaults={
            'name': a['name'], 'color': a['color'], 'is_active': True,
        })


def unseed(apps, schema_editor):
    Sector = apps.get_model('catalogs', 'Sector')
    LeadAlloy = apps.get_model('catalogs', 'LeadAlloy')
    LeadAlloy.objects.filter(code__in=['LIGA_0', 'LIGA_4', 'LIGA_5', 'LIGA_6']).delete()
    Sector.objects.filter(name__in=[
        'Teleiras', 'Boleira', 'Moinho', 'Masseira',
        'Empastadeira', 'Montagem', 'Formação',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_base, reverse_code=unseed),
    ]