# Generated by Django 5.1.15 on 2026-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_seed_base_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ('start_time', 'name'), 'verbose_name': 'turno', 'verbose_name_plural': 'turnos'},
        ),
        migrations.AddField(
            model_name='shift',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Marque quando for um turno de hora extra. Nesse caso, os horários de início e fim ficam opcionais e podem ser definidos no apontamento.', verbose_name='hora extra'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora fim'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='hora início'),
        ),
    ]
