# Generated by Django 5.1.15 on 2026-07-09 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('registration', models.CharField(blank=True, default='', max_length=40, verbose_name='matrícula')),
                ('user', models.OneToOneField(blank=True, help_text='Vínculo opcional com usuário do sistema (login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='operators_o_name_362a57_idx'), models.Index(fields=['registration'], name='operators_o_registr_eb5802_idx')],
            },
        ),
    ]
