# Generated by Django 5.1.15 on 2026-07-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='operator',
            name='operators_o_registr_eb5802_idx',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='registration',
        ),
    ]
