# Generated by Django 5.1.15 on 2026-07-09 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_seed_base_data'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('production_date', models.DateField(db_index=True, verbose_name='data')),
                ('polarity', models.CharField(choices=[('POS', 'Positiva'), ('NEG', 'Negativa')], max_length=3, verbose_name='polaridade')),
                ('lot', models.CharField(help_text='Lote de 3 dígitos (001–999). Preenchido automaticamente.', max_length=3, verbose_name='lote')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('start_time', models.DateTimeField(verbose_name='hora início')),
                ('end_time', models.DateTimeField(verbose_name='hora fim')),
                ('grid_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grid_productions', to='catalogs.gridmodel', verbose_name='modelo')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grid_productions', to='catalogs.machine', verbose_name='máquina')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grid_productions', to='operators.operator', verbose_name='operador')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grid_productions', to='catalogs.shift', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'produção de grade',
                'verbose_name_plural': 'produções de grade',
                'ordering': ('-production_date', '-start_time'),
                'indexes': [models.Index(fields=['production_date', 'machine'], name='production__product_4291d7_idx'), models.Index(fields=['lot'], name='production__lot_6e8f1e_idx'), models.Index(fields=['polarity'], name='production__polarit_6309d6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='grid_prod_end_after_start'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='grid_prod_quantity_positive')],
            },
        ),
    ]
