# Generated by Django 5.1.15 on 2026-07-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_shift_options_shift_is_overtime_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('stop_start', models.DateTimeField(db_index=True, verbose_name='hora que parou')),
                ('stop_end', models.DateTimeField(db_index=True, verbose_name='hora que voltou')),
                ('note', models.TextField(blank=True, default='', verbose_name='observação')),
                ('grid_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='production.gridproduction', verbose_name='produção de grade')),
                ('reasons', models.ManyToManyField(help_text='Múltiplos motivos podem ser selecionados (RF-P02).', related_name='machine_stops', to='catalogs.stopreason', verbose_name='motivo(s)')),
            ],
            options={
                'verbose_name': 'parada de máquina',
                'verbose_name_plural': 'paradas de máquina',
                'ordering': ('-stop_start',),
                'indexes': [models.Index(fields=['stop_start', 'stop_end'], name='production__stop_st_6ff02d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stop_end__gt', models.F('stop_start'))), name='machine_stop_end_after_start')],
            },
        ),
    ]
