# Generated by Django 5.1.15 on 2026-07-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_shift_options_shift_is_overtime_and_more'),
        ('production', '0002_machinestop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasteProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('paste_date', models.DateField(db_index=True, verbose_name='data')),
                ('polarity', models.CharField(choices=[('POS', 'Positiva'), ('NEG', 'Negativa')], max_length=3, verbose_name='polaridade')),
                ('lot', models.CharField(help_text='Lote automático no formato EP{DDMMYYYY}. Não editável manualmente (RF-E02).', max_length=12, verbose_name='lote')),
                ('pasted_quantity', models.PositiveIntegerField(verbose_name='quantidade empastada')),
                ('panel_loss', models.PositiveIntegerField(default=0, verbose_name='perda em painel')),
                ('grid_loss', models.PositiveIntegerField(default=0, verbose_name='perda de grade')),
                ('grid_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paste_productions', to='catalogs.gridmodel', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'empaste',
                'verbose_name_plural': 'empastes',
                'ordering': ('-paste_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OxideConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='peso consumido (kg)')),
                ('paste_production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oxide_consumption', to='production.pasteproduction', verbose_name='empaste')),
            ],
            options={
                'verbose_name': 'consumo de óxido',
                'verbose_name_plural': 'consumos de óxido',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='pasteproduction',
            index=models.Index(fields=['paste_date'], name='production__paste_d_3e95aa_idx'),
        ),
        migrations.AddIndex(
            model_name='pasteproduction',
            index=models.Index(fields=['lot'], name='production__lot_b93d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='pasteproduction',
            index=models.Index(fields=['polarity'], name='production__polarit_bb3101_idx'),
        ),
        migrations.AddConstraint(
            model_name='pasteproduction',
            constraint=models.CheckConstraint(condition=models.Q(('pasted_quantity__gt', 0)), name='paste_prod_pasted_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='oxideconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='oxide_consumption_weight_positive'),
        ),
    ]
