# Generated by Django 5.1.15 on 2026-07-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_shift_options_shift_is_overtime_and_more'),
        ('production', '0003_pastes_sprint5'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('mass_date', models.DateField(db_index=True, verbose_name='data')),
                ('lead_lot', models.CharField(help_text='Informar o lote do chumbo consumido (Cadastro completo na Sprint 7).', max_length=40, verbose_name='lote do chumbo')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='peso (kg)')),
                ('polarity', models.CharField(choices=[('POS', 'Positiva'), ('NEG', 'Negativa')], max_length=3, verbose_name='polaridade')),
                ('discarded_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='peso descartado (kg)')),
                ('mass_remainder_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='sobra de massa (kg)')),
                ('oxide_excess_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='excesso de óxido (kg)')),
                ('ready_mass_excess_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='excesso de massa pronta (kg)')),
                ('additive_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='peso do aditivo (kg)')),
            ],
            options={
                'verbose_name': 'masseira',
                'verbose_name_plural': 'masseiras',
                'ordering': ('-mass_date', '-id'),
                'indexes': [models.Index(fields=['mass_date'], name='production__mass_da_3cbd58_idx'), models.Index(fields=['polarity'], name='production__polarit_cdb198_idx'), models.Index(fields=['lead_lot'], name='production__lead_lo_2a7baf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('assembly_date', models.DateField(db_index=True, verbose_name='data')),
                ('lot', models.CharField(max_length=40, verbose_name='lote')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('positive_ep', models.CharField(help_text='Lote do empaste positivo utilizado.', max_length=40, verbose_name='EP positiva')),
                ('negative_ep', models.CharField(help_text='Lote do empaste negativo utilizado.', max_length=40, verbose_name='EP negativa')),
                ('note', models.TextField(blank=True, default='', verbose_name='observação')),
                ('grid_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='catalogs.gridmodel', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'montagem',
                'verbose_name_plural': 'montagens',
                'ordering': ('-assembly_date', '-id'),
                'indexes': [models.Index(fields=['assembly_date'], name='production__assembl_1fc240_idx'), models.Index(fields=['lot'], name='production__lot_e2e4e2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='assembly_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('formation_date', models.DateField(db_index=True, verbose_name='data')),
                ('table_number', models.PositiveSmallIntegerField(verbose_name='número da mesa')),
                ('battery_lot', models.CharField(max_length=40, verbose_name='lote da bateria')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('grid_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='catalogs.gridmodel', verbose_name='modelo da bateria')),
            ],
            options={
                'verbose_name': 'formação',
                'verbose_name_plural': 'formações',
                'ordering': ('-formation_date', '-table_number'),
                'indexes': [models.Index(fields=['formation_date'], name='production__formati_14bc0f_idx'), models.Index(fields=['table_number'], name='production__table_n_dbda05_idx'), models.Index(fields=['battery_lot'], name='production__battery_deeead_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='formation_quantity_positive')],
            },
        ),
    ]
