# Generated by Django 5.1.15 on 2026-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_sprint6_masseira_montagem_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massproduction',
            name='oxide_excess_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='adição de óxido (kg)'),
        ),
        migrations.AlterField(
            model_name='massproduction',
            name='ready_mass_excess_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='adição de massa pronta (kg)'),
        ),
        migrations.AlterField(
            model_name='massproduction',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='peso óxido (kg)'),
        ),
    ]
